/**
 * PoC Scaffolder.
 *
 * Generates the initial proof-of-concept project structure from a
 * `node-ts-vitest` template. Creates all required files for a working
 * TypeScript + Vitest project.
 *
 * Contract: specs/002-poc-generation/contracts/poc-output.md
 */
import { writeFile, mkdir, access } from 'node:fs/promises';
import { join, dirname } from 'node:path';

import type { TechStack } from '../shared/schemas/session.js';
import type { WorkshopSession } from '../shared/schemas/session.js';

// ── Types ────────────────────────────────────────────────────────────────────

export interface ScaffoldContext {
  /** Kebab-case project name derived from idea title */
  projectName: string;
  /** Original idea title */
  ideaTitle: string;
  /** Idea description from workshop */
  ideaDescription: string;
  /** Tech stack to use */
  techStack: TechStack;
  /** Summary of the implementation plan */
  planSummary: string;
  /** Workshop session ID */
  sessionId: string;
  /** Output directory (absolute path) */
  outputDir: string;
}

export interface TemplateFile {
  /** Path relative to outputDir */
  path: string;
  /** File content string or generator function */
  content: string | ((ctx: ScaffoldContext) => string);
  /** Skip writing if file already exists (default: true) */
  skipIfExists?: boolean;
}

export interface ScaffoldResult {
  /** Files that were created */
  createdFiles: string[];
  /** Files that were skipped because they already existed */
  skippedFiles: string[];
  /** The scaffold context used */
  context: ScaffoldContext;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Convert an idea title to a kebab-case project name.
 */
export function toKebabCase(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .substring(0, 64);
}

/**
 * Check if a file exists.
 */
async function fileExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

// ── Template definitions ─────────────────────────────────────────────────────

const NODE_TS_VITEST_TEMPLATE: TemplateFile[] = [
  {
    path: '.gitignore',
    skipIfExists: false,
    content: `node_modules/
dist/
coverage/
*.tsbuildinfo
.env
`,
  },

  {
    path: 'package.json',
    skipIfExists: true,
    content: (ctx) =>
      JSON.stringify(
        {
          name: ctx.projectName,
          version: '0.1.0',
          private: true,
          type: 'module',
          scripts: {
            build: 'tsc',
            start: 'node dist/index.js',
            test: 'vitest run',
          },
          dependencies: {},
          devDependencies: {
            typescript: '^5.0.0',
            vitest: '^3.0.0',
            '@types/node': '^20.0.0',
          },
        },
        null,
        2,
      ) + '\n',
  },

  {
    path: 'tsconfig.json',
    skipIfExists: true,
    content: JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'Node16',
          moduleResolution: 'Node16',
          strict: true,
          outDir: 'dist',
          rootDir: 'src',
          declaration: true,
          esModuleInterop: true,
          skipLibCheck: true,
        },
        include: ['src'],
      },
      null,
      2,
    ) + '\n',
  },

  {
    path: 'README.md',
    skipIfExists: true,
    content: (ctx) => `# ${ctx.ideaTitle}

${ctx.ideaDescription}

## Generated by

sofIA — AI Discovery Workshop CLI  
Session: \`${ctx.sessionId}\`  
Generated: ${new Date().toISOString()}

## Prerequisites

- Node.js 20+
- npm 9+

## Quick Start

\`\`\`bash
npm install
npm test
npm start
\`\`\`

## How It Works

${ctx.planSummary}

## Technology Stack

- **Language**: ${ctx.techStack.language}
- **Runtime**: ${ctx.techStack.runtime}
- **Test Runner**: ${ctx.techStack.testRunner}
${ctx.techStack.framework ? `- **Framework**: ${ctx.techStack.framework}\n` : ''}
`,
  },

  {
    path: 'src/index.ts',
    skipIfExists: true,
    content: (ctx) => `/**
 * ${ctx.ideaTitle}
 *
 * ${ctx.ideaDescription}
 *
 * Generated by sofIA (session: ${ctx.sessionId})
 */

/**
 * Main entry point for the ${ctx.projectName} PoC.
 *
 * TODO: Implement the core functionality described in the plan.
 * The test file (tests/index.test.ts) describes the expected behavior.
 */
export function main(): string {
  return 'Hello from ${ctx.projectName}!';
}

// Run if called directly
const isMain = process.argv[1]?.endsWith('index.js') || process.argv[1]?.endsWith('index.ts');
if (isMain) {
  console.log(main());
}
`,
  },

  {
    path: 'tests/index.test.ts',
    skipIfExists: true,
    content: (ctx) => `/**
 * Tests for ${ctx.ideaTitle} PoC.
 *
 * These tests describe the expected behavior of the implementation.
 * They are intentionally failing initially — the Ralph loop will
 * iteratively fix the implementation until they pass.
 *
 * Generated by sofIA (session: ${ctx.sessionId})
 */
import { describe, it, expect } from 'vitest';
import { main } from '../src/index.js';

describe('${ctx.projectName}', () => {
  it('should initialize successfully', () => {
    const result = main();
    expect(result).toBeDefined();
    expect(typeof result).toBe('string');
  });

  it('should implement core functionality', () => {
    // TODO: sofIA Ralph loop will refine this test to match the actual implementation
    // Plan: ${ctx.planSummary.substring(0, 200)}
    const result = main();
    expect(result).toContain('${ctx.projectName}');
  });
});
`,
  },

  {
    path: '.sofia-metadata.json',
    skipIfExists: false,
    content: (ctx) =>
      JSON.stringify(
        {
          sessionId: ctx.sessionId,
          featureSpec: '002-poc-generation',
          generatedAt: new Date().toISOString(),
          ideaTitle: ctx.ideaTitle,
          totalIterations: 0,
          finalStatus: null,
          terminationReason: null,
          techStack: {
            language: ctx.techStack.language.toLowerCase(),
            runtime: ctx.techStack.runtime.toLowerCase(),
            testRunner: ctx.techStack.testRunner,
          },
        },
        null,
        2,
      ) + '\n',
  },
];

// ── PocScaffolder ────────────────────────────────────────────────────────────

/**
 * Generates a PoC project scaffold from the `node-ts-vitest` template.
 *
 * Accepts a ScaffoldContext derived from a workshop session and creates
 * all required files. Files that already exist and have `skipIfExists: true`
 * are skipped to allow resuming a partial scaffold.
 */
export class PocScaffolder {
  private readonly template: TemplateFile[];

  constructor(template?: TemplateFile[]) {
    this.template = template ?? NODE_TS_VITEST_TEMPLATE;
  }

  /**
   * Build a ScaffoldContext from a workshop session.
   */
  static buildContext(session: WorkshopSession, outputDir: string): ScaffoldContext {
    const idea = session.ideas?.find((i) => i.id === session.selection?.ideaId);
    const ideaTitle = idea?.title ?? 'AI PoC';
    const ideaDescription = idea?.description ?? 'A proof-of-concept AI application.';

    const planSummary = session.plan?.architectureNotes
      ? session.plan.architectureNotes
      : session.plan?.milestones?.map((m) => m.title).join(', ') ?? 'See plan for details';

    const techStack: TechStack = {
      language: 'TypeScript',
      runtime: 'Node.js 20',
      testRunner: 'npm test',
      buildCommand: 'npm run build',
      framework: undefined,
    };

    // Infer framework from plan if present
    if (session.plan?.architectureNotes) {
      const notes = session.plan.architectureNotes.toLowerCase();
      if (notes.includes('express')) techStack.framework = 'Express';
      else if (notes.includes('fastapi')) techStack.framework = 'FastAPI';
      else if (notes.includes('next')) techStack.framework = 'Next.js';
    }

    return {
      projectName: toKebabCase(ideaTitle),
      ideaTitle,
      ideaDescription,
      techStack,
      planSummary,
      sessionId: session.sessionId,
      outputDir,
    };
  }

  /**
   * Scaffold the PoC project into the output directory.
   *
   * Creates all template files, respecting skipIfExists.
   * Returns lists of created and skipped files.
   */
  async scaffold(context: ScaffoldContext): Promise<ScaffoldResult> {
    await mkdir(context.outputDir, { recursive: true });

    const createdFiles: string[] = [];
    const skippedFiles: string[] = [];

    for (const templateFile of this.template) {
      const fullPath = join(context.outputDir, templateFile.path);
      const shouldSkip = templateFile.skipIfExists !== false;

      if (shouldSkip && (await fileExists(fullPath))) {
        skippedFiles.push(templateFile.path);
        continue;
      }

      // Ensure parent directory exists
      const parentDir = dirname(fullPath);
      await mkdir(parentDir, { recursive: true });

      // Generate content
      const content =
        typeof templateFile.content === 'function'
          ? templateFile.content(context)
          : templateFile.content;

      await writeFile(fullPath, content, 'utf-8');
      createdFiles.push(templateFile.path);
    }

    return { createdFiles, skippedFiles, context };
  }

  /**
   * Get the list of file paths in the template.
   */
  getTemplateFiles(): string[] {
    return this.template.map((f) => f.path);
  }
}

// ── Output Validator ─────────────────────────────────────────────────────────

export interface ValidationResult {
  valid: boolean;
  missingFiles: string[];
  errors: string[];
}

/**
 * Validate that a scaffold directory meets the poc-output contract requirements.
 */
export async function validatePocOutput(outputDir: string): Promise<ValidationResult> {
  const requiredFiles = [
    'package.json',
    'README.md',
    'tsconfig.json',
    '.gitignore',
    '.sofia-metadata.json',
  ];

  const missingFiles: string[] = [];
  const errors: string[] = [];

  // Check required files
  for (const file of requiredFiles) {
    const exists = await fileExists(join(outputDir, file));
    if (!exists) {
      missingFiles.push(file);
    }
  }

  // Check package.json has test script
  if (!missingFiles.includes('package.json')) {
    try {
      const { readFile } = await import('node:fs/promises');
      const pkgContent = await readFile(join(outputDir, 'package.json'), 'utf-8');
      const pkg = JSON.parse(pkgContent) as { scripts?: Record<string, string> };
      if (!pkg.scripts?.test) {
        errors.push('package.json is missing "test" script');
      }
    } catch {
      errors.push('package.json is not valid JSON');
    }
  }

  // Check for at least one .ts file in src/
  const { readdir } = await import('node:fs/promises');
  let hasSrcTs = false;
  try {
    const srcFiles = await readdir(join(outputDir, 'src'));
    hasSrcTs = srcFiles.some((f) => f.endsWith('.ts'));
  } catch {
    // src/ doesn't exist
  }
  if (!hasSrcTs) {
    errors.push('No TypeScript files found in src/');
  }

  // Check for at least one .test.ts file in tests/
  let hasTestFile = false;
  try {
    const testFiles = await readdir(join(outputDir, 'tests'));
    hasTestFile = testFiles.some((f) => f.endsWith('.test.ts'));
  } catch {
    // tests/ doesn't exist
  }
  if (!hasTestFile) {
    errors.push('No test files found in tests/');
  }

  return {
    valid: missingFiles.length === 0 && errors.length === 0,
    missingFiles,
    errors,
  };
}
